### ISSUE TITLE
__init__() got an unexpected keyword argument 'syntax'

### ISSUE THREAD

**Issue by 736980900** [chromium/dom-distiller#14]
I try to run ant test ,but i got this issues.help me please~

protoc:
    [apply] Traceback (most recent call last):
    [apply]   File "protoc_plugins/gwt_overlay.py", line 12, in <module>
    [apply]     from util import plugin, plugin_protos, writer
    [apply]   File "/mnt/ssd2/dom-distiller/dom-distiller/protoc_plugins/util/plugin.py", line 7, in <module>
    [apply]     import plugin_protos
    [apply]   File "/mnt/ssd2/dom-distiller/dom-distiller/protoc_plugins/util/plugin_protos.py", line 23, in <module>
    [apply]     import plugin_pb2
    [apply]   File "/mnt/ssd2/dom-distiller/dom-distiller/protoc_plugins/util/../../out/proto/python/google/protobuf/compiler/plugin_pb2.py", line 25, in <module>
    [apply]     dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
    [apply] TypeError: __init__() got an unexpected keyword argument 'syntax'
    [apply] --gwt_overlay_out: protoc-gen-gwt_overlay: Plugin failed with status code 1.

**Comment by jayesh-srivastava** [comment]
Hi, can I work on this issue if it's still available? Can you please explain a little further as to what exactly the issue is?
